[project]
name = "hdu-auto-login-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "playwright>=1.55.0",
    "pyinstaller>=6.16.0",
    "schedule>=1.2.2",
]
